# From: https://hub.docker.com/search?q=microsoft&type=image&image_filter=store%2Cofficial&category=languages&operating_system=linux

FROM mcr.microsoft.com/dotnet/aspnet:5.0 as base

WORKDIR /app

#EXPOSE 5080
#EXPOSE 5443

#ENV ASPNETCORE_URLS=http://+:5080
#ENV ASPNETCORE_URLS=http://+:5080;https://+:5443
#ENV ASPNETCORE_ENVIRONMENT=Development
#ASPNETCORE_URLS=https://localhost;http://localhost
#ENV ASPNETCORE_HTTPS_PORT=5443
#ENV ASPNETCORE_HTTP_PORT=5080

########################################################################################################################
# BUILD
########################################################################################################################

FROM mcr.microsoft.com/dotnet/sdk:5.0 as build

WORKDIR "/src"

COPY ["ExampleApi.csproj", "./"] 

RUN dotnet restore "ExampleApi.csproj"

COPY [".", "."] 

WORKDIR "/src/."

RUN dotnet build "ExampleApi.csproj" --configuration Release --output /build

FROM build AS publish

RUN dotnet publish "ExampleApi.csproj" --configuration Release --output /publish 

########################################################################################################################
# RUNTIME
########################################################################################################################

FROM base as runtime

WORKDIR /app

COPY --from=publish ["/publish", "."]

ENTRYPOINT ["dotnet", "ExampleApi.dll"]